services:
  - type: web
    name: urugendo-api
    env: python
    rootDir: urugendo
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false          # paste your Neon DATABASE_URL in the Render dashboard
      - key: SECRET_KEY
        generateValue: true  # Render auto-generates a secure random value
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: MTN_MOMO_BASE_URL
        value: https://sandbox.momodeveloper.mtn.com
      - key: MTN_MOMO_ENVIRONMENT
        value: sandbox
      - key: MTN_MOMO_CURRENCY
        value: RWF
      - key: AIRTEL_BASE_URL
        value: https://openapi.airtel.africa
      - key: AIRTEL_ENVIRONMENT
        value: sandbox
      - key: APP_NAME
        value: Urugendo
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.12.0"
